import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Variable } from "lucide-react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${inter.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-20 overflow-x-hidden bg-[#F0F0F0]">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}

//subheading - roboto
//display bold d2 - roboto 3.5rem, 4rem lh, #FFFFFF
//Sub_heading-semibold/sub5 - roboto w-600 2rem, 2.5rem lh, #242323
//Paragraph-regular/p5 - roboto
//Paragraph-regular/p3 - roboto w--400, .875rem size, 1.375rem lh, #606060
//Paragraph-semibold/p3 - roboto, .875rem, 1.375rem lineheight w-600 #242323
//Heading-semibold/h3 - roboto, w-600, 1.25rem, 1.75rem lh, #242323